services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    
  web:
    build:
      context: ./kepler
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./kepler:/kepler
      - /kepler/node_modules

    depends_on:
      - db
  db:
    image: postgres:16.2
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: