services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - static:/static

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend:/app/build
      - /frontend/node_modules

    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - api
      - web

  db:
    image: postgres:16.2
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  static:
  frontend:
  postgres_data: