services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

    depends_on:
      - db
  db:
    image: postgres:16.2
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"
     #- POSTGRES_DB=kepler
     #- POSTGRES_USER=kepler
     #- POSTGRES_PASSWORD=keplerAstronomy

volumes:
  postgres_data: