# Generated by Django 5.0.4 on 2024-04-11 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Address',
            fields=[
                ('email_address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('event_Description', models.CharField(max_length=1024)),
                ('start_Time', models.DateTimeField()),
                ('end_Time', models.DateTimeField()),
                ('notify', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_Types',
            fields=[
                ('subscription_Type_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('subscription_Type_Name', models.CharField(max_length=128)),
                ('subscription_Type_Description', models.CharField(max_length=1024)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('password_hash', models.CharField(max_length=1024)),
                ('active', models.BooleanField()),
                ('time_inserted', models.DateTimeField()),
                ('time_updated', models.DateTimeField()),
                ('email_address_id', models.ForeignKey(db_column='email_address_id', on_delete=django.db.models.deletion.PROTECT, to='astronomy.email_address')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing_List',
            fields=[
                ('email_List_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('subscribe_Date', models.DateTimeField()),
                ('unsubscribe_Date', models.DateTimeField()),
                ('customer_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='astronomy.customer')),
                ('email_Address_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='astronomy.email_address')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Notifications',
            fields=[
                ('event_Notification_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('notification_Time', models.DateTimeField()),
                ('event_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astronomy.event')),
                ('email_List_ID', models.ForeignKey(db_column='email_list_id', on_delete=django.db.models.deletion.CASCADE, to='astronomy.mailing_list')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_Features',
            fields=[
                ('subscription_Features_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('feature_Name', models.CharField(max_length=256)),
                ('feature_Description', models.CharField(max_length=1024)),
                ('subscription_Type_ID', models.ForeignKey(db_column='subscription_type_id', on_delete=django.db.models.deletion.CASCADE, to='astronomy.subscription_types')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('start_Time', models.DateTimeField()),
                ('end_Time', models.DateTimeField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astronomy.customer')),
                ('subscription_Type_ID', models.ForeignKey(db_column='subscription_type_id', on_delete=django.db.models.deletion.PROTECT, to='astronomy.subscription_types')),
            ],
        ),
    ]
