# Generated by Django 5.0.4 on 2024-04-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomy', '0002_rename_end_time_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
